name: facts_clock
description: A digital clock with time-digit number facts
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Open Sans
      fonts:
        - asset: third_party/Open_Sans/OpenSans-Regular.ttf
    - family: Fjalla One
      fonts:
        - asset: third_party/Fjalla_One/FjallaOne-Regular.ttf
  assets:
    - ./assets/data.json
